import BachThesisLean.Cubic.BraceSimplicity
import BachThesisLean.Cubic.TightCutBalance

namespace BachThesisLean
namespace BipartiteMultigraph

universe u v w

variable {X : Type u} {Y : Type v} {E : Type w}
variable [Fintype X] [Fintype Y] [Fintype E]
variable [DecidableEq X] [DecidableEq Y] [DecidableEq E]

/-!
# Strict Hall inequality for cubic braces

For a left set `S`, close it by adjoining every right neighbour.  No edge can
leave this shore from the left.  If the right-neighbour set has the same size
as `S`, matching-coveredness and connectedness fail across the resulting cut.
If it has size exactly `|S|+1`, the matching-balance identity makes that shore
a tight cut.  A brace excludes both possibilities whenever at least two left
vertices remain outside `S`.
-/

/-- The shore generated by a set of left vertices and all their right
neighbours. -/
noncomputable def leftNeighborShore (G : BipartiteMultigraph X Y E)
    (S : Finset X) : Finset (X ⊕ Y) := by
  classical
  exact Finset.univ.filter fun v =>
    match v with
    | .inl x => x ∈ S
    | .inr y => y ∈ S.biUnion G.rightNeighborSet

@[simp] theorem mem_leftNeighborShore_inl
    (G : BipartiteMultigraph X Y E) (S : Finset X) (x : X) :
    (Sum.inl x : X ⊕ Y) ∈ G.leftNeighborShore S ↔ x ∈ S := by
  classical
  simp [leftNeighborShore]

@[simp] theorem mem_leftNeighborShore_inr
    (G : BipartiteMultigraph X Y E) (S : Finset X) (y : Y) :
    (Sum.inr y : X ⊕ Y) ∈ G.leftNeighborShore S ↔
      y ∈ S.biUnion G.rightNeighborSet := by
  classical
  simp [leftNeighborShore]

@[simp] theorem cutLeftVertices_leftNeighborShore
    (G : BipartiteMultigraph X Y E) (S : Finset X) :
    cutLeftVertices (G.leftNeighborShore S) = S := by
  classical
  ext x
  simp

@[simp] theorem cutRightVertices_leftNeighborShore
    (G : BipartiteMultigraph X Y E) (S : Finset X) :
    cutRightVertices (G.leftNeighborShore S) =
      S.biUnion G.rightNeighborSet := by
  classical
  ext y
  simp

/-- By construction, no edge leaves the generated shore from its left side. -/
@[simp] theorem cutFromLeft_leftNeighborShore
    (G : BipartiteMultigraph X Y E) (S : Finset X) :
    G.cutFromLeft (G.leftNeighborShore S) = ∅ := by
  classical
  ext e
  constructor
  · intro he
    have hcut := (G.mem_cutFromLeft (G.leftNeighborShore S) e).1 he
    have hx : G.left e ∈ S := by simpa using hcut.1
    have hy : G.right e ∈ S.biUnion G.rightNeighborSet := by
      rw [Finset.mem_biUnion]
      refine ⟨G.left e, hx, ?_⟩
      exact (mem_rightNeighborSet G (G.left e) (G.right e)).2
        ⟨e, (G.mem_leftIncident (G.left e) e).2 rfl, rfl⟩
    exact False.elim (hcut.2 (by simpa using hy))
  · intro he
    simp at he

/-- If `S` is nonempty and leaves at least two left vertices outside, its
neighbour-closed shore is nontrivial. -/
theorem leftNeighborShore_isNontrivial
    (G : BipartiteMultigraph X Y E) (hG : G.IsCubic)
    (S : Finset X) (hS : S.Nonempty)
    (hroom : S.card + 2 ≤ Fintype.card X) :
    IsNontrivialCutShore (G.leftNeighborShore S) := by
  classical
  constructor
  · obtain ⟨x, hxS⟩ := hS
    have hdeg : (G.leftIncident x).card = 3 := by
      simpa using hG (.inl x)
    have hpos : 0 < (G.leftIncident x).card := by omega
    obtain ⟨e, heI⟩ := Finset.card_pos.mp hpos
    have hyN : G.right e ∈ S.biUnion G.rightNeighborSet := by
      rw [Finset.mem_biUnion]
      refine ⟨x, hxS, ?_⟩
      exact (mem_rightNeighborSet G x (G.right e)).2 ⟨e, heI, rfl⟩
    apply Finset.one_lt_card_iff_nontrivial.mpr
    refine ⟨.inl x, by simp [hxS], .inr (G.right e), ?_, by simp⟩
    simpa using hyN
  · let ι : X ↪ X ⊕ Y := ⟨Sum.inl, Sum.inl_injective⟩
    let T : Finset (X ⊕ Y) := ((Finset.univ : Finset X) \ S).map ι
    have hTsub : T ⊆ (G.leftNeighborShore S)ᶜ := by
      intro z hz
      obtain ⟨x, hx, rfl⟩ := Finset.mem_map.mp hz
      have hxnot : x ∉ S := (Finset.mem_sdiff.mp hx).2
      apply Finset.mem_compl.mpr
      intro hxW
      exact hxnot ((G.mem_leftNeighborShore_inl S x).1 hxW)
    have hScard : S.card ≤ Fintype.card X := by
      simpa using Finset.card_le_card (Finset.subset_univ S)
    have houtCard : ((Finset.univ : Finset X) \ S).card =
        Fintype.card X - S.card := by
      rw [Finset.card_sdiff (Finset.subset_univ S)]
      simp
    have hTcard : T.card = Fintype.card X - S.card := by
      simp [T, houtCard]
    have hTgt : 1 < T.card := by
      rw [hTcard]
      omega
    exact lt_of_lt_of_le hTgt (Finset.card_le_card hTsub)

/-- If the generated right-neighbour set has exactly one more vertex than the
left set, matching balance forces the generated shore to be tight. -/
theorem leftNeighborShore_isTightCut_of_card_eq_add_one
    (G : BipartiteMultigraph X Y E) (S : Finset X)
    (hN : (S.biUnion G.rightNeighborSet).card = S.card + 1) :
    G.IsTightCut (G.leftNeighborShore S) := by
  classical
  intro P hP
  have hbal := hP.cut_orientation_balance (G.leftNeighborShore S)
  rw [G.cutLeftVertices_leftNeighborShore,
    G.cutRightVertices_leftNeighborShore,
    G.cutFromLeft_leftNeighborShore] at hbal
  simp only [Finset.inter_empty, Finset.card_empty, Nat.add_zero] at hbal
  rw [hN] at hbal
  have hright :
      (P ∩ G.cutFromRight (G.leftNeighborShore S)).card = 1 := by
    omega
  have hcut : G.edgeCut (G.leftNeighborShore S) =
      G.cutFromRight (G.leftNeighborShore S) := by
    rw [G.edgeCut_eq_oriented_union, G.cutFromLeft_leftNeighborShore]
    simp
  rw [hcut]
  exact hright

/-- In a cubic brace, every nonempty left set that leaves two left vertices
outside has at least two more right neighbours than left vertices.  This is the
strict Hall form of 2-extendability used by the square argument. -/
theorem IsBrace.rightNeighbor_union_card_ge_add_two
    {G : BipartiteMultigraph X Y E} (hbrace : G.IsBrace) (hG : G.IsCubic)
    (S : Finset X) (hS : S.Nonempty)
    (hroom : S.card + 2 ≤ Fintype.card X) :
    S.card + 2 ≤ (S.biUnion G.rightNeighborSet).card := by
  classical
  let N : Finset Y := S.biUnion G.rightNeighborSet
  let W : Finset (X ⊕ Y) := G.leftNeighborShore S
  have hHall : S.card ≤ N.card := by
    simpa [N] using G.cubic_hall_condition hG S
  have hnontriv : IsNontrivialCutShore W := by
    simpa [W] using G.leftNeighborShore_isNontrivial hG S hS hroom
  by_contra hnot
  have hnotN : ¬ S.card + 2 ≤ N.card := by
    simpa [N] using hnot
  have hle : N.card ≤ S.card + 1 := by omega
  have hcases : N.card = S.card ∨ N.card = S.card + 1 := by omega
  rcases hcases with hEq | hSucc
  · have hW : W.Nonempty := by
      have hcard : 0 < W.card := lt_trans Nat.zero_lt_one hnontriv.1
      exact Finset.card_pos.mp hcard
    have hWc : Wᶜ.Nonempty := by
      have hcard : 0 < Wᶜ.card := lt_trans Nat.zero_lt_one hnontriv.2
      exact Finset.card_pos.mp hcard
    obtain ⟨g, hgcut⟩ :=
      hbrace.1.1.edgeCut_nonempty_of_nonempty_shores hW hWc
    have hgRight : g ∈ G.cutFromRight W := by
      have h := hgcut
      rw [G.edgeCut_eq_oriented_union,
        show G.cutFromLeft W = ∅ by simp [W]] at h
      simpa using h
    obtain ⟨P, hP, hgP⟩ := hbrace.1.2.2 g
    have hbal := hP.cut_orientation_balance W
    have hleft : cutLeftVertices W = S := by simp [W]
    have hright : cutRightVertices W = N := by simp [W, N]
    have hleftCut : G.cutFromLeft W = ∅ := by simp [W]
    rw [hleft, hright, hleftCut] at hbal
    simp only [Finset.inter_empty, Finset.card_empty, Nat.add_zero] at hbal
    rw [hEq] at hbal
    have hzero : (P ∩ G.cutFromRight W).card = 0 := by omega
    have hgInter : g ∈ P ∩ G.cutFromRight W :=
      Finset.mem_inter.mpr ⟨hgP, hgRight⟩
    have hpos : 0 < (P ∩ G.cutFromRight W).card :=
      Finset.card_pos.mpr ⟨g, hgInter⟩
    omega
  · have hT : G.IsTightCut W := by
      simpa [W, N] using
        G.leftNeighborShore_isTightCut_of_card_eq_add_one S hSucc
    exact hbrace.2 W hnontriv hT

end BipartiteMultigraph
end BachThesisLean
